spring:
  application:
    name: code-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/code}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
      ssl:
        enabled: false
      repositories:
        enabled: false

      jedis:
        pool:
          enabled: true
          min-idle: ${REDIS_MIN_IDLE:1}
          max-active: ${REDIS_MAX_ACTIVE:3}
          max-idle: ${REDIS_MAX_IDLE:1}

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true


# temporary storage location
storage:
  location: temp-dir

cloudinary:
  url: ${CLOUDINARY_URL:cloudinary://API_KEY:API_SECRET@CLOUD_NAME}

springdoc:
  api-docs:
    enabled: ${SWAGGER_UI:true}