spring:
  application:
    name: code-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/code}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      pool-name: code-pool
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      allow-pool-suspension: false

  data:
    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: true
      repositories:
        enabled: false

      jedis:
        pool:
          enabled: true
          min-idle: ${REDIS_MIN_IDLE:1}
          max-active: ${REDIS_MAX_ACTIVE:3}
          max-idle: ${REDIS_MAX_IDLE:1}

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true

# temporary storage location
storage:
  location: temp-dir

cloudinary:
  url: ${CLOUDINARY_URL:NO_CLOUDINARY_URL_WAS_PROVIDED}