services:
  application:
    container_name: code_backend
    build:
      context: .
      target: builder
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/code
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres_container:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/code

  postgres_container:
    image: postgres:15
    container_name: code_db
    environment:
      POSTGRES_DB: code
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - code_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redislabs/redismod
    container_name: redis_container
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  code_db: