import { OfficeMember } from "@/types/backendTypes";

export const officeMembers: OfficeMember[] = [
  {
    id: "1",
    image: { uri: "/about.svg", id: "img1", host: "CLOUDINARY" },
    firstName: "Alice",
    lastName: "Johnson",
    position: "President",
    linkedin: "https://linkedin.com/in/alicejohnson",
    instagram: "https://instagram.com/alicejohnson",
    addedAt: new Date("2024-01-10"),
  },
  {
    id: "2",
    image: { uri: "/about.svg", id: "img2", host: "CLOUDINARY" },
    firstName: "Bob",
    lastName: "Smith",
    position: "Vice President",
    linkedin: "https://linkedin.com/in/bobsmith",
    instagram: "https://instagram.com/bobsmith",
    addedAt: new Date("2024-01-12"),
  },
  {
    id: "3",
    image: { uri: "/about.svg", id: "img3", host: "CLOUDINARY" },
    firstName: "Charlie",
    lastName: "Lee",
    position: "Chief Development Officer",
    linkedin: "https://linkedin.com/in/charlielee",
    instagram: "https://instagram.com/charlielee",
    addedAt: new Date("2024-01-15"),
  },
  {
    id: "4",
    image: { uri: "/about.svg", id: "img4", host: "CLOUDINARY" },
    firstName: "Diana",
    lastName: "Martinez",
    position: "Treasury",
    linkedin: "https://linkedin.com/in/dianamartinez",
    instagram: "https://instagram.com/dianamartinez",
    addedAt: new Date("2024-01-17"),
  },
  {
    id: "5",
    image: { uri: "/about.svg", id: "img5", host: "CLOUDINARY" },
    firstName: "Ethan",
    lastName: "Brown",
    position: "Secretary General",
    linkedin: "https://linkedin.com/in/ethanbrown",
    instagram: "https://instagram.com/ethanbrown",
    addedAt: new Date("2024-01-20"),
  },
  {
    id: "6",
    image: { uri: "/about.svg", id: "img6", host: "CLOUDINARY" },
    firstName: "Fiona",
    lastName: "Davis",
    position: "Consultant",
    linkedin: "https://linkedin.com/in/fionadavis",
    instagram: "https://instagram.com/fionadavis",
    addedAt: new Date("2024-01-22"),
  },
  {
    id: "7",
    image: { uri: "/about.svg", id: "img7", host: "CLOUDINARY" },
    firstName: "George",
    lastName: "Wilson",
    position: "Consultant",
    linkedin: "https://linkedin.com/in/georgewilson",
    instagram: "https://instagram.com/georgewilson",
    addedAt: new Date("2024-01-25"),
  },
  {
    id: "8",
    image: { uri: "/about.svg", id: "img8", host: "CLOUDINARY" },
    firstName: "Hannah",
    lastName: "Taylor",
    position: "Chief Media Officer",
    linkedin: "https://linkedin.com/in/hannahtaylor",
    instagram: "https://instagram.com/hannahtaylor",
    addedAt: new Date("2024-01-27"),
  },
  {
    id: "9",
    image: { uri: "/about.svg", id: "img9", host: "CLOUDINARY" },
    firstName: "Ian",
    lastName: "Anderson",
    position: "Chief Logistics Officer",
    linkedin: "https://linkedin.com/in/iananderson",
    instagram: "https://instagram.com/iananderson",
    addedAt: new Date("2024-01-30"),
  },
  {
    id: "10",
    image: { uri: "/about.svg", id: "img10", host: "CLOUDINARY" },
    firstName: "Julia",
    lastName: "Moore",
    position: "Frontend Dev",
    linkedin: "https://linkedin.com/in/juliamoore",
    instagram: "https://instagram.com/juliamoore",
    addedAt: new Date("2024-02-02"),
  },
  {
    id: "11",
    image: { uri: "/girl.svg", id: "img11", host: "CLOUDINARY" },
    firstName: "Kevin",
    lastName: "White",
    position: "Frontend Dev",
    linkedin: "https://linkedin.com/in/kevinwhite",
    instagram: "https://instagram.com/kevinwhite",
    addedAt: new Date("2024-02-05"),
  },
  {
    id: "12",
    image: { uri: "/girl.svg", id: "img12", host: "CLOUDINARY" },
    firstName: "Laura",
    lastName: "Harris",
    position: "Vice HR",
    linkedin: "https://linkedin.com/in/lauraharris",
    instagram: "https://instagram.com/lauraharris",
    addedAt: new Date("2024-02-08"),
  },
  {
    id: "13",
    image: { uri: "/girl.svg", id: "img13", host: "CLOUDINARY" },
    firstName: "Michael",
    lastName: "Clark",
    position: "Vice SG",
    linkedin: "https://linkedin.com/in/michaelclark",
    instagram: "https://instagram.com/michaelclark",
    addedAt: new Date("2024-02-10"),
  },
  {
    id: "14",
    image: { uri: "/girl.svg", id: "img14", host: "CLOUDINARY" },
    firstName: "Nina",
    lastName: "Lewis",
    position: "Vice Treasury",
    linkedin: "https://linkedin.com/in/ninalewis",
    instagram: "https://instagram.com/ninalewis",
    addedAt: new Date("2024-02-12"),
  },
  {
    id: "15",
    image: { uri: "/girl.svg", id: "img15", host: "CLOUDINARY" },
    firstName: "Oliver",
    lastName: "King",
    position: "Chief Communication Officer",
    linkedin: "https://linkedin.com/in/oliverking",
    instagram: "https://instagram.com/oliverking",
    addedAt: new Date("2024-02-15"),
  },
  {
    id: "16",
    image: { uri: "/about.svg", id: "img4", host: "CLOUDINARY" },
    firstName: "Diana",
    lastName: "Martinez",
    position: "Human Resources",
    linkedin: "https://linkedin.com/in/dianamartinez",
    instagram: "https://instagram.com/dianamartinez",
    addedAt: new Date("2024-01-17"),
  },
];


export const devs: OfficeMember[] = [
  {
    id: "1",
    image: { uri: "/photo2.png", id: "img1", host: "CLOUDINARY" },
    firstName: "Mouad",
    lastName: "Sadik",
    position: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/mouad-sadik-5b8907257/",
    instagram: "https://www.instagram.com/mouad_sadik_?igsh=NXoyNzhjamozZTFt",
    addedAt: new Date("2025-09-09"),
  },
  {
    id: "2",
    image: { uri: "https://avatars.githubusercontent.com/u/183768832?v=4", id: "img2", host: "CLOUDINARY" },
    firstName: "Badreddine",
    lastName: "Ziane",
    position: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/ziane-badr-eddine-baa394337",
    instagram: "https://www.instagram.com/ziane_badreddine__",
    addedAt: new Date("2025-09-09"),
  },
  {
    id: "3",
    image: { uri: "/student.svg", id: "img3", host: "CLOUDINARY" },
    firstName: "Zakaria",
    lastName: "ES-SAOUDY",
    position: "Backend Developer",
    linkedin: " https://www.linkedin.com/in/zakaria-es-saoudy-b6a683271?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    instagram: " https://www.instagram.com/zakaria_sdd?igsh=MXI5dzVld3Rqd2VtMg==",
    addedAt: new Date("2025-09-09"),
  },
  {
    id: "4",
    image: { uri: "/girl.svg", id: "img4", host: "CLOUDINARY" },
    firstName: "Zahra",
    lastName: "Ait Baali",
    position: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/zahra-ait-baali?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    instagram: "https://www.instagram.com/zhi.ro.31?igsh=aGg1eGdvdTdmOTBn",
    addedAt: new Date("2025-09-09"),
  },
  {
    id: "5",
    image: { uri: "/about.svg", id: "img5", host: "CLOUDINARY" },
    firstName: "Ilyass",
    lastName: "Bougati",
    position: "Project leader - backend - devops",
    linkedin: "https://www.linkedin.com/in/ilyass-bougati-093a60293",
    instagram: "https://www.instagram.com/i.bougati?igsh=N2t4YmhldDhva3Jp",
    addedAt: new Date("2025-09-09"),
  },
  {
    id: "6",
    image: { uri: "/fz.jfif", id: "img6", host: "CLOUDINARY" },
    firstName: "Fatima ezzahra",
    lastName: "EL BOUAZIZI",
    position: "Backend Developer",
    linkedin: "https://www.linkedin.com/in/fatima-ezzahra-el-bouazizi-21aa64281/",
    instagram: "https://www.instagram.com/fvtimvezzahrv",
    addedAt: new Date("2025-09-09"),
  },
  {
    id: "7",
    image: { uri: "/abdelah.jfif", id: "img7", host: "CLOUDINARY" },
    firstName: "Abdellah",
    lastName: "Darni",
    position: "Backend Developer – Admin Dashboard",
    linkedin: "https://www.linkedin.com/in/darni-abdellah",
    instagram: "https://www.instagram.com/abdellah_darni",
    addedAt: new Date("2025-09-09"),
  },
]